/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PCxxCC1
 */
public class Principal extends javax.swing.JFrame {
     
    MySQL db = new MySQL();
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conectar_Base = new javax.swing.JButton();
        Automoviles_Stock = new javax.swing.JButton();
        Clientes = new javax.swing.JButton();
        Empleados = new javax.swing.JButton();
        Ventas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Servicios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1336, 768));
        getContentPane().setLayout(null);

        Conectar_Base.setBackground(new java.awt.Color(204, 204, 204));
        Conectar_Base.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Conectar_Base.setText("Conectar con Base de Datos");
        Conectar_Base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conectar_BaseActionPerformed(evt);
            }
        });
        getContentPane().add(Conectar_Base);
        Conectar_Base.setBounds(1070, 10, 240, 40);

        Automoviles_Stock.setBackground(new java.awt.Color(0, 0, 204));
        Automoviles_Stock.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        Automoviles_Stock.setForeground(new java.awt.Color(255, 255, 255));
        Automoviles_Stock.setText("Autmoviles en Stock");
        Automoviles_Stock.setEnabled(false);
        Automoviles_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Automoviles_StockActionPerformed(evt);
            }
        });
        getContentPane().add(Automoviles_Stock);
        Automoviles_Stock.setBounds(30, 120, 300, 45);

        Clientes.setBackground(new java.awt.Color(0, 0, 204));
        Clientes.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Clientes.setText("Clientes");
        Clientes.setEnabled(false);
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        getContentPane().add(Clientes);
        Clientes.setBounds(260, 240, 277, 45);

        Empleados.setBackground(new java.awt.Color(0, 0, 204));
        Empleados.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Empleados.setText("Empleados");
        Empleados.setEnabled(false);
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(Empleados);
        Empleados.setBounds(510, 390, 277, 45);

        Ventas.setBackground(new java.awt.Color(0, 0, 204));
        Ventas.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        Ventas.setForeground(new java.awt.Color(255, 255, 255));
        Ventas.setText("Ventas");
        Ventas.setEnabled(false);
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        getContentPane().add(Ventas);
        Ventas.setBounds(760, 520, 277, 45);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        jLabel4.setText("Bienvenido usuario");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(4, 4, 470, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1380, 60);

        Servicios.setBackground(new java.awt.Color(0, 0, 204));
        Servicios.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Servicios.setText("Servicios");
        Servicios.setEnabled(false);
        Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(Servicios);
        Servicios.setBounds(1010, 660, 277, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Principal.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Conectar_BaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conectar_BaseActionPerformed
        try {
            db.MySQLConnection("root", "", "");
            db.createDB("agencia");
            db.createTableAutos("autos");
            db.createTableClientes("clientes");
            db.createTableEmpleados("empleados");
            db.createTableVentas("ventas");
            db.createTableServicios("servicios");
            db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Conectar_Base.setEnabled(false);
        Automoviles_Stock.setEnabled(true);
        Clientes.setEnabled(true);
        Empleados.setEnabled(true);
        Ventas.setEnabled(true);
        Servicios.setEnabled(true);
    }//GEN-LAST:event_Conectar_BaseActionPerformed

    private void Automoviles_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Automoviles_StockActionPerformed
        Ventana_Autos_Menu ventana = new Ventana_Autos_Menu();
        ventana.setVisible(true);
    }//GEN-LAST:event_Automoviles_StockActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        Ventana_Clientes_Menu ventana = new Ventana_Clientes_Menu();
        ventana.setVisible(true);
    }//GEN-LAST:event_ClientesActionPerformed

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed
        Ventana_Empleados_Menu ventana = new Ventana_Empleados_Menu();
        ventana.setVisible(true);
    }//GEN-LAST:event_EmpleadosActionPerformed

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        Ventana_Ventas_Menu ventana = new Ventana_Ventas_Menu();
        ventana.setVisible(true);
    }//GEN-LAST:event_VentasActionPerformed

    private void ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosActionPerformed
        Ventana_Servicios_Menu ventana = new Ventana_Servicios_Menu();
        ventana.setVisible(true);
    }//GEN-LAST:event_ServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Automoviles_Stock;
    private javax.swing.JButton Clientes;
    private javax.swing.JButton Conectar_Base;
    private javax.swing.JButton Empleados;
    private javax.swing.JButton Servicios;
    private javax.swing.JButton Ventas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
