/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class Ventana_Obtener_Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Obtener_Empleados
     */
    public Ventana_Obtener_Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldOEApellidos = new javax.swing.JTextField();
        jTextFieldRFC = new javax.swing.JTextField();
        jTextFieldOENombres = new javax.swing.JTextField();
        Obtener_Clientes_Buscar = new javax.swing.JButton();
        jTextFieldOESexo = new javax.swing.JTextField();
        Obtener_Clientes_Cancelar = new javax.swing.JButton();
        jTextFieldOEFecha_Nacimiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOEDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldOEColonia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldOETelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldOEPuesto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(799, 603));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inserte RFC del empleado:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 310, 40);

        jTextFieldOEApellidos.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOEApellidos);
        jTextFieldOEApellidos.setBounds(130, 140, 261, 29);

        jTextFieldRFC.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jTextFieldRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRFCActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRFC);
        jTextFieldRFC.setBounds(335, 72, 330, 40);

        jTextFieldOENombres.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOENombres);
        jTextFieldOENombres.setBounds(130, 190, 261, 29);

        Obtener_Clientes_Buscar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Obtener_Clientes_Buscar.setText("Buscar");
        Obtener_Clientes_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_Clientes_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Clientes_Buscar);
        Obtener_Clientes_Buscar.setBounds(530, 10, 110, 33);

        jTextFieldOESexo.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOESexo);
        jTextFieldOESexo.setBounds(90, 280, 190, 29);

        Obtener_Clientes_Cancelar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Obtener_Clientes_Cancelar.setText("Cancelar");
        Obtener_Clientes_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_Clientes_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Clientes_Cancelar);
        Obtener_Clientes_Cancelar.setBounds(660, 10, 120, 33);

        jTextFieldOEFecha_Nacimiento.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jTextFieldOEFecha_Nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOEFecha_NacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldOEFecha_Nacimiento);
        jTextFieldOEFecha_Nacimiento.setBounds(210, 340, 297, 29);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 90, 30);

        jTextFieldOEDireccion.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOEDireccion);
        jTextFieldOEDireccion.setBounds(110, 450, 297, 29);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre(s)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 100, 30);

        jTextFieldOEColonia.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOEColonia);
        jTextFieldOEColonia.setBounds(90, 390, 297, 29);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 280, 60, 30);

        jTextFieldOETelefono.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOETelefono);
        jTextFieldOETelefono.setBounds(110, 510, 150, 29);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de nacimiento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 340, 190, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 450, 100, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Colonia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 390, 80, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfono");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 510, 90, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Puesto");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 230, 70, 30);

        jTextFieldOEPuesto.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOEPuesto);
        jTextFieldOEPuesto.setBounds(120, 230, 297, 29);

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Consultar todos los registros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 530, 220, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel12.setText("Consultar empleados");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(4, -6, 460, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 970, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Obtener_Empleados.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-250, -150, 1090, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRFCActionPerformed
    public String condicionRFC;
    private void Obtener_Clientes_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_Clientes_BuscarActionPerformed
        MySQL db = new MySQL();
           try {
            db.MySQLConnection("root", "", "agencia");
            condicionRFC = jTextFieldRFC.getText();
            String sql = "SELECT Apellidos, Nombres, Puesto, Sexo, Fecha_Nacimiento, Direccion, Colonia, Telefono FROM empleados WHERE RFC = '"+condicionRFC+"' ";
            Statement st = MySQL.Conexion.createStatement();
            java.sql.ResultSet resultSet;
            resultSet = st.executeQuery(sql);
            while (resultSet.next()) {
                jTextFieldOEApellidos.setText(resultSet.getString("Apellidos"));
                jTextFieldOENombres.setText(resultSet.getString("Nombres"));
                jTextFieldOEPuesto.setText(resultSet.getString("Puesto"));
                jTextFieldOESexo.setText(resultSet.getString("Sexo"));
                jTextFieldOEFecha_Nacimiento.setText(resultSet.getString("Fecha_Nacimiento"));
                jTextFieldOEDireccion.setText(resultSet.getString("Direccion"));
                jTextFieldOEColonia.setText(resultSet.getString("Colonia"));
                jTextFieldOETelefono.setText(resultSet.getString("Telefono"));    
            }
            db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Obtener_Autos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error en la consulta de registros, revise que ha introducido un RFC existente.");
        }
    }//GEN-LAST:event_Obtener_Clientes_BuscarActionPerformed

    private void Obtener_Clientes_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_Clientes_CancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_Obtener_Clientes_CancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MySQL db = new MySQL();
        try {
            db.MySQLConnection("root", "", "agencia");
            db.getValuesEmpleados("empleados");
            db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Obtener_Autos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldOEFecha_NacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOEFecha_NacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOEFecha_NacimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Obtener_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Obtener_Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Obtener_Clientes_Buscar;
    private javax.swing.JButton Obtener_Clientes_Cancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldOEApellidos;
    private javax.swing.JTextField jTextFieldOEColonia;
    private javax.swing.JTextField jTextFieldOEDireccion;
    private javax.swing.JTextField jTextFieldOEFecha_Nacimiento;
    private javax.swing.JTextField jTextFieldOENombres;
    private javax.swing.JTextField jTextFieldOEPuesto;
    private javax.swing.JTextField jTextFieldOESexo;
    private javax.swing.JTextField jTextFieldOETelefono;
    private javax.swing.JTextField jTextFieldRFC;
    // End of variables declaration//GEN-END:variables
}
