/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

/**
 *
 * @author Luis
 */
public class Ventana_Servicios_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Servicios_Menu
     */
    public Ventana_Servicios_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_Servicios = new javax.swing.JButton();
        Obtener_Servicios = new javax.swing.JButton();
        Eliminar_Servicios = new javax.swing.JButton();
        Regresar_ServiciosaPrincipal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 512));
        getContentPane().setLayout(null);

        Agregar_Servicios.setBackground(new java.awt.Color(0, 0, 204));
        Agregar_Servicios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Agregar_Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_Servicios.setText("Agregar servicio");
        Agregar_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_ServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar_Servicios);
        Agregar_Servicios.setBounds(80, 300, 180, 27);

        Obtener_Servicios.setBackground(new java.awt.Color(0, 0, 204));
        Obtener_Servicios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Obtener_Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Obtener_Servicios.setText("Obtener servicio");
        Obtener_Servicios.setActionCommand("Obtener servicios");
        Obtener_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_ServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Servicios);
        Obtener_Servicios.setBounds(277, 300, 180, 27);

        Eliminar_Servicios.setBackground(new java.awt.Color(0, 0, 204));
        Eliminar_Servicios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Eliminar_Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Servicios.setText("Eliminar servicio");
        Eliminar_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_ServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar_Servicios);
        Eliminar_Servicios.setBounds(480, 300, 150, 27);

        Regresar_ServiciosaPrincipal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Regresar_ServiciosaPrincipal.setText("Regresar");
        Regresar_ServiciosaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_ServiciosaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar_ServiciosaPrincipal);
        Regresar_ServiciosaPrincipal.setBounds(530, 10, 100, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setText("Menú servicios");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(4, -6, 460, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_Servicios.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-440, -410, 1300, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_ServiciosActionPerformed
        Ventana_Agregar_Servicios ventana = new Ventana_Agregar_Servicios();
        ventana.setVisible(true);
    }//GEN-LAST:event_Agregar_ServiciosActionPerformed

    private void Obtener_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_ServiciosActionPerformed
        Ventana_Obtener_Servicios ventana = new Ventana_Obtener_Servicios();
        ventana.setVisible(true);
    }//GEN-LAST:event_Obtener_ServiciosActionPerformed

    private void Eliminar_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_ServiciosActionPerformed
        Ventana_Eliminar_Servicios ventana = new Ventana_Eliminar_Servicios();
        ventana.setVisible(true);
    }//GEN-LAST:event_Eliminar_ServiciosActionPerformed

    private void Regresar_ServiciosaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_ServiciosaPrincipalActionPerformed
        this.dispose();
    }//GEN-LAST:event_Regresar_ServiciosaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Servicios_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Servicios_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Servicios;
    private javax.swing.JButton Eliminar_Servicios;
    private javax.swing.JButton Obtener_Servicios;
    private javax.swing.JButton Regresar_ServiciosaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
