/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class Ventana_Obtener_Servicios extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Obtener_Servicios
     */
    public Ventana_Obtener_Servicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldOSProblemas_Generales = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOSFecha_Recepcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldOSID_Cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldOSFecha_Entrega = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldOSRFC = new javax.swing.JTextField();
        jTextFieldOSNumero_Serie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Obtener_Clientes_Buscar = new javax.swing.JButton();
        Obtener_Clientes_Cancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldOSCambio_Frenos = new javax.swing.JTextField();
        jTextFieldOSAfinacion = new javax.swing.JTextField();
        jTextFieldOSCambio_Aceite = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(799, 603));
        getContentPane().setLayout(null);

        jTextFieldOSProblemas_Generales.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSProblemas_Generales);
        jTextFieldOSProblemas_Generales.setBounds(220, 470, 262, 29);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setText("Cambio de aceite");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 380, 160, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setText("RFC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 60, 30);

        jTextFieldOSFecha_Recepcion.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSFecha_Recepcion);
        jTextFieldOSFecha_Recepcion.setBounds(190, 290, 170, 29);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel9.setText("Afinación");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 380, 100, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setText("Número de serie");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 220, 150, 30);

        jTextFieldOSID_Cliente.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSID_Cliente);
        jTextFieldOSID_Cliente.setBounds(150, 220, 92, 29);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel10.setText("Cambio de frenos");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 380, 160, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setText("ID del cliente");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 130, 30);

        jTextFieldOSFecha_Entrega.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSFecha_Entrega);
        jTextFieldOSFecha_Entrega.setBounds(570, 290, 180, 29);

        jTextField1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 80, 111, 35);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setText("Fecha de recepción");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 290, 180, 30);

        jTextFieldOSRFC.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSRFC);
        jTextFieldOSRFC.setBounds(80, 140, 260, 29);

        jTextFieldOSNumero_Serie.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSNumero_Serie);
        jTextFieldOSNumero_Serie.setBounds(450, 220, 300, 29);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setText("Fecha de entrega");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 290, 160, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel11.setText("Problemas generales");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 470, 190, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setText("Inserte ID del servicio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(19, 82, 253, 29);

        Obtener_Clientes_Buscar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Obtener_Clientes_Buscar.setText("Buscar");
        Obtener_Clientes_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_Clientes_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Clientes_Buscar);
        Obtener_Clientes_Buscar.setBounds(540, 10, 110, 33);

        Obtener_Clientes_Cancelar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Obtener_Clientes_Cancelar.setText("Cancelar");
        Obtener_Clientes_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_Clientes_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Clientes_Cancelar);
        Obtener_Clientes_Cancelar.setBounds(660, 10, 120, 33);

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Consultar todos los registros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 530, 220, 30);

        jTextFieldOSCambio_Frenos.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSCambio_Frenos);
        jTextFieldOSCambio_Frenos.setBounds(680, 380, 90, 30);

        jTextFieldOSAfinacion.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSAfinacion);
        jTextFieldOSAfinacion.setBounds(390, 380, 90, 30);

        jTextFieldOSCambio_Aceite.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOSCambio_Aceite);
        jTextFieldOSCambio_Aceite.setBounds(180, 380, 88, 29);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel12.setText("Consultar servicio");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(4, -6, 460, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 970, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Obtener_Ventas.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-200, -130, 1040, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MySQL db = new MySQL();
        try {
            db.MySQLConnection("root", "", "agencia");
            db.getValuesServicios("servicios");
            db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Obtener_Autos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public String condicionID_Servicio;
    private void Obtener_Clientes_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_Clientes_BuscarActionPerformed
        MySQL db = new MySQL();
        try {
            db.MySQLConnection("root", "", "agencia");
            condicionID_Servicio = jTextField1.getText();
            String sql = "SELECT RFC, ID_Cliente, Numero_Serie, Fecha_Recepcion, Fecha_Entrega, Cambio_Aceite, Afinacion, Cambio_Frenos,"
                    + " Problemas_Generales FROM servicios WHERE ID_Servicio = '"+condicionID_Servicio+"'";
            Statement st = MySQL.Conexion.createStatement();
            java.sql.ResultSet resultSet;
            resultSet = st.executeQuery(sql);
            while (resultSet.next()) {
                jTextFieldOSRFC.setText(resultSet.getString("RFC"));
                jTextFieldOSID_Cliente.setText(resultSet.getString("ID_Cliente"));
                jTextFieldOSNumero_Serie.setText(resultSet.getString("Numero_Serie"));
                jTextFieldOSFecha_Recepcion.setText(resultSet.getString("Fecha_Recepcion"));
                jTextFieldOSFecha_Entrega.setText(resultSet.getString("Fecha_Entrega"));
                jTextFieldOSCambio_Aceite.setText(resultSet.getString("Cambio_Aceite"));
                jTextFieldOSAfinacion.setText(resultSet.getString("Afinacion"));
                jTextFieldOSCambio_Frenos.setText(resultSet.getString("Cambio_Frenos"));
                jTextFieldOSProblemas_Generales.setText(resultSet.getString("Problemas_Generales"));
            }
            db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Obtener_Ventas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error en la consulta de registros, revise que ha introducido un ID de servicio existente.");
        }
    }//GEN-LAST:event_Obtener_Clientes_BuscarActionPerformed

    private void Obtener_Clientes_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_Clientes_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_Obtener_Clientes_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Obtener_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Obtener_Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Obtener_Clientes_Buscar;
    private javax.swing.JButton Obtener_Clientes_Cancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldOSAfinacion;
    private javax.swing.JTextField jTextFieldOSCambio_Aceite;
    private javax.swing.JTextField jTextFieldOSCambio_Frenos;
    private javax.swing.JTextField jTextFieldOSFecha_Entrega;
    private javax.swing.JTextField jTextFieldOSFecha_Recepcion;
    private javax.swing.JTextField jTextFieldOSID_Cliente;
    private javax.swing.JTextField jTextFieldOSNumero_Serie;
    private javax.swing.JTextField jTextFieldOSProblemas_Generales;
    private javax.swing.JTextField jTextFieldOSRFC;
    // End of variables declaration//GEN-END:variables
}
