/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luis
 */
public class Ventana_Agregar_Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Agregar_Ventas
     */
    public Ventana_Agregar_Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldId_Venta = new javax.swing.JTextField();
        jTextFieldRFC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID_Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumero_Serie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldForma_Pago = new javax.swing.JTextField();
        Aceptar_Autos = new javax.swing.JButton();
        Cancelar_Autos = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(965, 606));
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 430, 110, 29);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Forma de pago");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 490, 180, 29);

        jTextFieldId_Venta.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldId_Venta);
        jTextFieldId_Venta.setBounds(440, 130, 130, 30);

        jTextFieldRFC.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldRFC);
        jTextFieldRFC.setBounds(440, 190, 250, 36);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Venta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 130, 130, 29);

        jTextFieldID_Cliente.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldID_Cliente);
        jTextFieldID_Cliente.setBounds(440, 260, 250, 36);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RFC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 190, 90, 29);

        jTextFieldFecha.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jTextFieldFecha.setText("AAAA/MM/DD");
        getContentPane().add(jTextFieldFecha);
        jTextFieldFecha.setBounds(440, 380, 170, 36);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Cliente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 260, 130, 29);

        jTextFieldPrecio.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldPrecio);
        jTextFieldPrecio.setBounds(440, 430, 250, 36);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Número de serie");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 320, 190, 29);

        jTextFieldNumero_Serie.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldNumero_Serie);
        jTextFieldNumero_Serie.setBounds(440, 320, 250, 36);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 380, 110, 29);

        jTextFieldForma_Pago.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldForma_Pago);
        jTextFieldForma_Pago.setBounds(440, 490, 250, 36);

        Aceptar_Autos.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Aceptar_Autos.setText("Aceptar");
        Aceptar_Autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar_AutosActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar_Autos);
        Aceptar_Autos.setBounds(541, 10, 140, 31);

        Cancelar_Autos.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Cancelar_Autos.setText("Cancelar");
        Cancelar_Autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_AutosActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar_Autos);
        Cancelar_Autos.setBounds(700, 10, 160, 31);

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel13.setText("Ingreso de ventas");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(4, -6, 460, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 970, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_Ventas.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Aceptar_AutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar_AutosActionPerformed
        MySQL db = new MySQL();
        try {
            db.MySQLConnection("root", "", "agencia");
            db.insertDataVentas("ventas", jTextFieldId_Venta.getText(),
                jTextFieldRFC.getText(),
                jTextFieldID_Cliente.getText(),
                jTextFieldNumero_Serie.getText(),
                jTextFieldFecha.getText(),
                jTextFieldPrecio.getText(),
                jTextFieldForma_Pago.getText());
        db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Agregar_Autos.class.getName()).log(Level.SEVERE, null, ex);
        }  
        this.dispose();
    }//GEN-LAST:event_Aceptar_AutosActionPerformed

    private void Cancelar_AutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_AutosActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar_AutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Agregar_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar_Autos;
    private javax.swing.JButton Cancelar_Autos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldForma_Pago;
    private javax.swing.JTextField jTextFieldID_Cliente;
    private javax.swing.JTextField jTextFieldId_Venta;
    private javax.swing.JTextField jTextFieldNumero_Serie;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldRFC;
    // End of variables declaration//GEN-END:variables
}
