/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PCxxCC1
 */
public class Ventana_Obtener_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Obtener_Clientes
     */
    public Ventana_Obtener_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        Obtener_Clientes_Buscar = new javax.swing.JButton();
        Obtener_Clientes_Cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldOCApellidos = new javax.swing.JTextField();
        jTextFieldOCNombre = new javax.swing.JTextField();
        jTextFieldOCFecha_Nacimiento = new javax.swing.JTextField();
        jTextFieldOCDireccion = new javax.swing.JTextField();
        jTextFieldOCColonia = new javax.swing.JTextField();
        jTextFieldOCTelefono = new javax.swing.JTextField();
        jTextFieldOCSexo = new javax.swing.JTextField();
        Obtener_Clientes_Todos = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(799, 603));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inserte ID del cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 250, 31);

        jTextFieldID.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldID);
        jTextFieldID.setBounds(280, 60, 120, 31);

        Obtener_Clientes_Buscar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Obtener_Clientes_Buscar.setText("Consultar");
        Obtener_Clientes_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_Clientes_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Clientes_Buscar);
        Obtener_Clientes_Buscar.setBounds(499, 10, 140, 33);

        Obtener_Clientes_Cancelar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Obtener_Clientes_Cancelar.setText("Cancelar");
        Obtener_Clientes_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_Clientes_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Clientes_Cancelar);
        Obtener_Clientes_Cancelar.setBounds(660, 10, 120, 33);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 100, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre(s)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 210, 100, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 270, 60, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de nacimiento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 330, 190, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 410, 100, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Colonia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 440, 80, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfono");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 480, 90, 30);

        jTextFieldOCApellidos.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jTextFieldOCApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOCApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldOCApellidos);
        jTextFieldOCApellidos.setBounds(130, 150, 196, 29);

        jTextFieldOCNombre.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOCNombre);
        jTextFieldOCNombre.setBounds(130, 210, 224, 29);

        jTextFieldOCFecha_Nacimiento.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOCFecha_Nacimiento);
        jTextFieldOCFecha_Nacimiento.setBounds(220, 330, 150, 29);

        jTextFieldOCDireccion.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOCDireccion);
        jTextFieldOCDireccion.setBounds(110, 410, 290, 29);

        jTextFieldOCColonia.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOCColonia);
        jTextFieldOCColonia.setBounds(540, 440, 224, 29);

        jTextFieldOCTelefono.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOCTelefono);
        jTextFieldOCTelefono.setBounds(140, 480, 171, 29);

        jTextFieldOCSexo.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        getContentPane().add(jTextFieldOCSexo);
        jTextFieldOCSexo.setBounds(100, 270, 140, 33);

        Obtener_Clientes_Todos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Obtener_Clientes_Todos.setText("Consultar todos los registros");
        Obtener_Clientes_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_Clientes_TodosActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Clientes_Todos);
        Obtener_Clientes_Todos.setBounds(550, 530, 220, 25);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel12.setText("Consultar clientes");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(4, -6, 460, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 970, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abstracto-azul-fondo-en-hd-5.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-60, -20, 940, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOCApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOCApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOCApellidosActionPerformed
public String condicionID_Cliente;
    private void Obtener_Clientes_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_Clientes_BuscarActionPerformed
        MySQL db = new MySQL();
           try {
            db.MySQLConnection("root", "", "agencia");
            condicionID_Cliente = jTextFieldID.getText();
            String sql = "SELECT Apellidos, Nombres, Sexo, Fecha_Nacimiento, Direccion, Colonia, Telefono FROM clientes WHERE ID_Cliente = '"+condicionID_Cliente+"'";
            Statement st = MySQL.Conexion.createStatement();
            java.sql.ResultSet resultSet;
            resultSet = st.executeQuery(sql);
            while (resultSet.next()) {
                jTextFieldOCApellidos.setText(resultSet.getString("Apellidos"));
                jTextFieldOCNombre.setText(resultSet.getString("Nombres"));
                jTextFieldOCSexo.setText(resultSet.getString("Sexo"));
                jTextFieldOCFecha_Nacimiento.setText(resultSet.getString("Fecha_Nacimiento"));
                jTextFieldOCDireccion.setText(resultSet.getString("Direccion"));
                jTextFieldOCColonia.setText(resultSet.getString("Colonia"));
                jTextFieldOCTelefono.setText(resultSet.getString("Telefono"));    
            }
            db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Obtener_Autos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error en la consulta de registros, revise que ha introducido un ID de cliente existente.");
        }
    }//GEN-LAST:event_Obtener_Clientes_BuscarActionPerformed

    private void Obtener_Clientes_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_Clientes_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_Obtener_Clientes_CancelarActionPerformed

    private void Obtener_Clientes_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_Clientes_TodosActionPerformed
        MySQL db = new MySQL();
        try {
            db.MySQLConnection("root", "", "agencia");
            db.getValuesClientes("clientes");
            db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Obtener_Autos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Obtener_Clientes_TodosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Obtener_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Obtener_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Obtener_Clientes_Buscar;
    private javax.swing.JButton Obtener_Clientes_Cancelar;
    private javax.swing.JButton Obtener_Clientes_Todos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldOCApellidos;
    private javax.swing.JTextField jTextFieldOCColonia;
    private javax.swing.JTextField jTextFieldOCDireccion;
    private javax.swing.JTextField jTextFieldOCFecha_Nacimiento;
    private javax.swing.JTextField jTextFieldOCNombre;
    private javax.swing.JTextField jTextFieldOCSexo;
    private javax.swing.JTextField jTextFieldOCTelefono;
    // End of variables declaration//GEN-END:variables
}
