/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luis
 */
public class Ventana_Eliminar_Venta extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Eliminar_Venta
     */
    public Ventana_Eliminar_Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Eliminar_Autos_Eliminar = new javax.swing.JButton();
        Elimnar_Autos_Cancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(637, 243));
        setMinimumSize(new java.awt.Dimension(637, 243));
        setPreferredSize(new java.awt.Dimension(637, 243));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Introducir ID de venta:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 90, 252, 29);

        jTextField1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 90, 100, 30);

        Eliminar_Autos_Eliminar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Eliminar_Autos_Eliminar.setText("ELIMINAR");
        Eliminar_Autos_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_Autos_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar_Autos_Eliminar);
        Eliminar_Autos_Eliminar.setBounds(350, 140, 150, 40);

        Elimnar_Autos_Cancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Elimnar_Autos_Cancelar.setText("CANCELAR");
        Elimnar_Autos_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Elimnar_Autos_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Elimnar_Autos_Cancelar);
        Elimnar_Autos_Cancelar.setBounds(510, 10, 120, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel12.setText("Eliminar venta");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(4, -6, 460, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 970, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar_Ventas.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-1010, -710, 1860, 1050);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Eliminar_Autos_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_Autos_EliminarActionPerformed
        MySQL db = new MySQL();
        try {
            db.MySQLConnection("root", "", "agencia");
            db.deleteRegistroVentas("ventas", jTextField1.getText());
            db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Eliminar_Autos.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.dispose();
    }//GEN-LAST:event_Eliminar_Autos_EliminarActionPerformed

    private void Elimnar_Autos_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Elimnar_Autos_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_Elimnar_Autos_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Eliminar_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Eliminar_Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar_Autos_Eliminar;
    private javax.swing.JButton Elimnar_Autos_Cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
