/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

/**
 *
 * @author PCxxCC1
 */
public class Ventana_Empleados_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Empleados_Menu
     */
    public Ventana_Empleados_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_Empleados = new javax.swing.JButton();
        Obtener_Empleados = new javax.swing.JButton();
        Eliminar_Empleados = new javax.swing.JButton();
        Regresar_EmpleadosaPrincipal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 512));
        getContentPane().setLayout(null);

        Agregar_Empleados.setBackground(new java.awt.Color(0, 0, 204));
        Agregar_Empleados.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Agregar_Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_Empleados.setText("Agregar empleado");
        Agregar_Empleados.setPreferredSize(new java.awt.Dimension(203, 27));
        Agregar_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_EmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar_Empleados);
        Agregar_Empleados.setBounds(10, 100, 180, 40);

        Obtener_Empleados.setBackground(new java.awt.Color(0, 0, 204));
        Obtener_Empleados.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Obtener_Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Obtener_Empleados.setText("Obtener empleados");
        Obtener_Empleados.setPreferredSize(new java.awt.Dimension(203, 27));
        Obtener_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_EmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Empleados);
        Obtener_Empleados.setBounds(210, 100, 190, 39);

        Eliminar_Empleados.setBackground(new java.awt.Color(0, 0, 204));
        Eliminar_Empleados.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Eliminar_Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Empleados.setText("Eliminar empleado");
        Eliminar_Empleados.setPreferredSize(new java.awt.Dimension(203, 27));
        Eliminar_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_EmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar_Empleados);
        Eliminar_Empleados.setBounds(420, 100, 203, 40);

        Regresar_EmpleadosaPrincipal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Regresar_EmpleadosaPrincipal.setText("Regresar");
        Regresar_EmpleadosaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_EmpleadosaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar_EmpleadosaPrincipal);
        Regresar_EmpleadosaPrincipal.setBounds(520, 10, 100, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setText("Menú empleados");
        jLabel4.setPreferredSize(new java.awt.Dimension(640, 512));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(4, -6, 460, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_Empleados.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-170, 0, 920, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_EmpleadosActionPerformed
        Ventana_Agregar_Empleados ventana = new Ventana_Agregar_Empleados();
        ventana.setVisible(true);
    }//GEN-LAST:event_Agregar_EmpleadosActionPerformed

    private void Obtener_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_EmpleadosActionPerformed
        Ventana_Obtener_Empleados ventana = new Ventana_Obtener_Empleados();
        ventana.setVisible(true);
    }//GEN-LAST:event_Obtener_EmpleadosActionPerformed

    private void Eliminar_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_EmpleadosActionPerformed
        Ventana_Eliminar_Empleados ventana = new Ventana_Eliminar_Empleados();
        ventana.setVisible(true);
    }//GEN-LAST:event_Eliminar_EmpleadosActionPerformed

    private void Regresar_EmpleadosaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_EmpleadosaPrincipalActionPerformed
        this.dispose();
    }//GEN-LAST:event_Regresar_EmpleadosaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Empleados_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Empleados_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Empleados;
    private javax.swing.JButton Eliminar_Empleados;
    private javax.swing.JButton Obtener_Empleados;
    private javax.swing.JButton Regresar_EmpleadosaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
