/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

/**
 *
 * @author PCxxCC1
 */
public class Ventana_Autos_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Autos_Menu
     */
    public Ventana_Autos_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_Autos = new javax.swing.JButton();
        Obtener_Autos = new javax.swing.JButton();
        Eliminar_Autos = new javax.swing.JButton();
        Regresar_AutosaPrincipal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 512));
        getContentPane().setLayout(null);

        Agregar_Autos.setBackground(new java.awt.Color(0, 0, 204));
        Agregar_Autos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Agregar_Autos.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_Autos.setText("Agregar Autmoviles");
        Agregar_Autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_AutosActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar_Autos);
        Agregar_Autos.setBounds(10, 420, 180, 50);

        Obtener_Autos.setBackground(new java.awt.Color(0, 0, 255));
        Obtener_Autos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Obtener_Autos.setForeground(new java.awt.Color(255, 255, 255));
        Obtener_Autos.setText("Obtener Automoviles");
        Obtener_Autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_AutosActionPerformed(evt);
            }
        });
        getContentPane().add(Obtener_Autos);
        Obtener_Autos.setBounds(210, 420, 210, 50);

        Eliminar_Autos.setBackground(new java.awt.Color(0, 0, 204));
        Eliminar_Autos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Eliminar_Autos.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Autos.setText("Eliminar Autmoviles");
        Eliminar_Autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_AutosActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar_Autos);
        Eliminar_Autos.setBounds(430, 420, 180, 50);

        Regresar_AutosaPrincipal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Regresar_AutosaPrincipal.setText("Regresar");
        Regresar_AutosaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_AutosaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar_AutosaPrincipal);
        Regresar_AutosaPrincipal.setBounds(510, 10, 110, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setText("Menú automóviles");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(4, -6, 460, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_Autos.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 50, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_AutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_AutosActionPerformed
        Ventana_Agregar_Autos ventana = new Ventana_Agregar_Autos();
        ventana.setVisible(true);
    }//GEN-LAST:event_Agregar_AutosActionPerformed

    private void Obtener_AutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_AutosActionPerformed
        Ventana_Obtener_Autos ventana = new Ventana_Obtener_Autos();
        ventana.setVisible(true);
    }//GEN-LAST:event_Obtener_AutosActionPerformed

    private void Eliminar_AutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_AutosActionPerformed
        Ventana_Eliminar_Autos ventana = new Ventana_Eliminar_Autos();
        ventana.setVisible(true);
    }//GEN-LAST:event_Eliminar_AutosActionPerformed

    private void Regresar_AutosaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_AutosaPrincipalActionPerformed
        this.dispose();
    }//GEN-LAST:event_Regresar_AutosaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Autos_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventana_Autos_Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Autos;
    private javax.swing.JButton Eliminar_Autos;
    private javax.swing.JButton Obtener_Autos;
    private javax.swing.JButton Regresar_AutosaPrincipal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
