/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PCxxCC1
 */
public class Ventana_Agregar_Autos extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Agregar_Autos
     */
    public Ventana_Agregar_Autos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNumero_Serie = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldAnio = new javax.swing.JTextField();
        jTextFieldConfig_Motor = new javax.swing.JTextField();
        jTextFieldTrans = new javax.swing.JTextField();
        jTextFieldEquipamiento = new javax.swing.JTextField();
        Aceptar_Autos = new javax.swing.JButton();
        Cancelar_Autos = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(969, 606));
        setMinimumSize(new java.awt.Dimension(969, 606));
        setPreferredSize(new java.awt.Dimension(969, 606));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de Serie");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 110, 210, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 160, 100, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 210, 110, 28);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 250, 70, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 300, 80, 28);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Color");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 350, 90, 28);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Configuración del Motor");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 400, 290, 28);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Transmisión");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 450, 160, 28);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Equipamiento");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 500, 180, 28);

        jTextFieldNumero_Serie.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldNumero_Serie);
        jTextFieldNumero_Serie.setBounds(520, 110, 214, 36);

        jTextFieldMarca.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldMarca);
        jTextFieldMarca.setBounds(520, 160, 214, 36);

        jTextFieldModelo.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldModelo);
        jTextFieldModelo.setBounds(520, 210, 214, 36);

        jTextFieldTipo.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldTipo);
        jTextFieldTipo.setBounds(520, 300, 214, 36);

        jTextFieldColor.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldColor);
        jTextFieldColor.setBounds(520, 340, 214, 36);

        jTextFieldAnio.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldAnio);
        jTextFieldAnio.setBounds(520, 250, 73, 40);

        jTextFieldConfig_Motor.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldConfig_Motor);
        jTextFieldConfig_Motor.setBounds(520, 400, 214, 36);

        jTextFieldTrans.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldTrans);
        jTextFieldTrans.setBounds(520, 450, 214, 36);

        jTextFieldEquipamiento.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jTextFieldEquipamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEquipamientoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEquipamiento);
        jTextFieldEquipamiento.setBounds(520, 500, 214, 36);

        Aceptar_Autos.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Aceptar_Autos.setText("Aceptar");
        Aceptar_Autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar_AutosActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar_Autos);
        Aceptar_Autos.setBounds(630, 10, 130, 30);

        Cancelar_Autos.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Cancelar_Autos.setText("Cancelar");
        Cancelar_Autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_AutosActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar_Autos);
        Cancelar_Autos.setBounds(781, 10, 150, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel12.setText("Ingreso de automóviles");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(4, -6, 460, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 970, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_Autos.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Aceptar_AutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar_AutosActionPerformed
        MySQL db = new MySQL();
        try {
            db.MySQLConnection("root", "", "agencia");
            db.insertDataAutos("autos", jTextFieldNumero_Serie.getText(),
                jTextFieldMarca.getText(),
                jTextFieldModelo.getText(),
                jTextFieldAnio.getText(),
                jTextFieldTipo.getText(),
                jTextFieldColor.getText(),
                jTextFieldConfig_Motor.getText(),
                jTextFieldTrans.getText(),
                jTextFieldEquipamiento.getText());
            } catch (Exception ex) {
            Logger.getLogger(Ventana_Agregar_Autos.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();    
        db.closeConnection();
    }//GEN-LAST:event_Aceptar_AutosActionPerformed

    private void Cancelar_AutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_AutosActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar_AutosActionPerformed

    private void jTextFieldEquipamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEquipamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEquipamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar_Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventana_Agregar_Autos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar_Autos;
    private javax.swing.JButton Cancelar_Autos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldConfig_Motor;
    private javax.swing.JTextField jTextFieldEquipamiento;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNumero_Serie;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFieldTrans;
    // End of variables declaration//GEN-END:variables
}
