/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PCxxCC1
 */
public class Ventana_Agregar_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Agregar_Clientes
     */
    public Ventana_Agregar_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldID_Cliente = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldFechaNacimiento = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldColonia = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox();
        Agregar_Clientes_Agregar = new javax.swing.JButton();
        Agregar_Clientes_Cancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(969, 606));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 100, 130, 29);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 150, 120, 29);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre(s)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 200, 130, 29);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 260, 70, 29);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de nacimiento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 310, 240, 29);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 360, 120, 29);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Colonia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 420, 100, 29);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfono");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 470, 110, 29);

        jTextFieldID_Cliente.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldID_Cliente);
        jTextFieldID_Cliente.setBounds(460, 90, 110, 36);

        jTextFieldApellidos.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldApellidos);
        jTextFieldApellidos.setBounds(460, 150, 230, 36);

        jTextFieldNombre.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(460, 200, 230, 36);

        jTextFieldFechaNacimiento.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jTextFieldFechaNacimiento.setText("AAAA/MM/DD");
        getContentPane().add(jTextFieldFechaNacimiento);
        jTextFieldFechaNacimiento.setBounds(460, 310, 190, 36);

        jTextFieldDireccion.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldDireccion);
        jTextFieldDireccion.setBounds(460, 360, 380, 36);

        jTextFieldColonia.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldColonia);
        jTextFieldColonia.setBounds(460, 410, 270, 36);

        jTextFieldTelefono.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        getContentPane().add(jTextFieldTelefono);
        jTextFieldTelefono.setBounds(460, 470, 220, 36);

        jComboBoxSexo.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(jComboBoxSexo);
        jComboBoxSexo.setBounds(460, 250, 170, 36);

        Agregar_Clientes_Agregar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Agregar_Clientes_Agregar.setText("Agregar");
        Agregar_Clientes_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_Clientes_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar_Clientes_Agregar);
        Agregar_Clientes_Agregar.setBounds(570, 10, 150, 30);

        Agregar_Clientes_Cancelar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Agregar_Clientes_Cancelar.setText("Cancelar");
        Agregar_Clientes_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_Clientes_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar_Clientes_Cancelar);
        Agregar_Clientes_Cancelar.setBounds(740, 10, 140, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel12.setText("Ingreso de clientes");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(4, -6, 460, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 970, 50);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_Clientes.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-370, 0, 1350, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_Clientes_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_Clientes_AgregarActionPerformed
        MySQL db = new MySQL();
        try {
            db.MySQLConnection("root", "", "agencia");
            db.insertDataClientes("clientes", jTextFieldID_Cliente.getText(),
                jTextFieldApellidos.getText(),
                jTextFieldNombre.getText(),
                jComboBoxSexo.getSelectedItem().toString(),  
                jTextFieldFechaNacimiento.getText(),
                jTextFieldDireccion.getText(),
                jTextFieldColonia.getText(),
                jTextFieldTelefono.getText());
        db.closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(Ventana_Agregar_Autos.class.getName()).log(Level.SEVERE, null, ex);
        }  
        this.dispose();
    }//GEN-LAST:event_Agregar_Clientes_AgregarActionPerformed

    private void Agregar_Clientes_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_Clientes_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_Agregar_Clientes_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Agregar_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Clientes_Agregar;
    private javax.swing.JButton Agregar_Clientes_Cancelar;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldColonia;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFechaNacimiento;
    private javax.swing.JTextField jTextFieldID_Cliente;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
